# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f320e771ddcbe9fc3a96fc8bc4d0ebfde41d7a51805f34be7e9889fef107873bcbd4fa7ee6a91e5535e0030d76e6b00eb9d972d18493815dc586faa342ee75

test:
  secret_key_base: 94be64de047fe574d58447f43225a58dd94c0d77fef674769a000945d4413d8f84b175859d565115161172721b624707a66a6223801b59230d7252e409e9042d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
